name: Build and deploy React app to Azure Web App - barbershop-front

on:
  push:
    branches:
      - login-main-menu
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          rm -rf node_modules
          npm install
          npm install --include=optional
          npm install @rollup/rollup-linux-x64-gnu --save-dev
          npm run build

      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download production build
        uses: actions/download-artifact@v4
        with:
          name: react-app
          path: dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BDF177F086F94E5097C9C3DC8450D25C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F2B4DBC18E6F4536BC15A082F69EBCDC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A5E7D1ADEC90411695D1B49E6B63706D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'barbershop-front'
          slot-name: 'Production'
          package: dist
